archive_project:
  artifacts:
    paths: []
  only:
    variables:
    - $PACKAGE_IOS == "1"
  script:
  - sed -i.bak -e "s/CODE_SIGN_IDENTITY = [^;]*;//g" -e "s/CODE_SIGN_STYLE = [^;]*/CODE_SIGN_STYLE = $CODE_SIGN_STYLE;CODE_SIGN_IDENTITY = \"$CODE_SIGN_IDENTITY\"/g" -e "s/DEVELOPMENT_TEAM = [^;]*/DEVELOPMENT_TEAM = $DEVELOPMENT_TEAM/g" -e "s/PROVISIONING_PROFILE_SPECIFIER = [^;]*;//g" -e "s/PRODUCT_BUNDLE_IDENTIFIER = [^;]*/PRODUCT_BUNDLE_IDENTIFIER = \"$PRODUCT_BUNDLE_IDENTIFIER\"; PROVISIONING_PROFILE_SPECIFIER = \"$PROVISIONING_PROFILE_SPECIFIER\"/g" -e "s/PROVISIONING_PROFILE = [^;]*/PROVISIONING_PROFILE = \"$PROVISIONING_PROFILE\"/g" ${IOS_PROJECT}/project.pbxproj
  - xcodebuild build -workspace $IOS_WORKSPACE -scheme $IOS_BUILD_SCHEME -configuration
    "Release" -DEBUG_INFORMATION_FORMAT='dwarf-with-dsym' -derivedDataPath build |
    xcpretty
  - mv ${IOS_PROJECT}/project.pbxproj.bak ${IOS_PROJECT}/project.pbxproj
  - cp -r build/Build/Products/Release-iphoneos/${IOS_TARGET_NAME}.app Payload/ &&
    zip -qr ${IOS_TARGET_NAME}_${CI_COMMIT_SHA}.ipa Payload
  - cat $IOS_VERSION_FILE
  - cp ${IOS_TARGET_NAME}_${CI_COMMIT_SHA}.ipa ~/artifacts/${IOS_DEPLOY_NAME}/${IOS_TARGET_NAME}_${CI_COMMIT_SHA}.ipa
  - python ~/artifacts/${IOS_DEPLOY_NAME}/ci_deploy_new_version.py ${CI_COMMIT_REF_NAME} ${CI_COMMIT_SHA}
  stage: archive
  tags:
  - ios
  variables:
    IOS_DEPLOY_NAME_REGION: ${IOS_DEPLOY_NAME}${PACKAGE_REGION}
before_script:
- export LC_CTYPE=en_US.UTF-8
- rm -rf build
- mkdir build
- cd $IOS_TARGET_NAME && ifconfig && pod install && cd ..
- rm -rf Payload
- mkdir Payload
stages:
- archive
variables:
  CI_VERSION: 1.0.0
  CODE_SIGN_IDENTITY: 'iPhone Distribution'
  CODE_SIGN_STYLE: 'Manual'
  DEVELOPMENT_TEAM: 'K889LGV7VJ'
  GIT_SUBMODULE_STRATEGY: 'recursive'
  IOS_BUILD_SCHEME: NoSMS
  IOS_DEPLOY_NAME: 'nosms'
  IOS_PROJECT: NoSMS.xcodeproj
  IOS_TARGET_NAME: MustAuth
  IOS_VERSION_FILE: NoSMS/Info.plist
  IOS_WORKSPACE: NoSMS.xcworkspace
  LC_CTYPE: en_US.UTF-8
  PACKAGE_CHANNEL: ios-01000
  PRODUCT_BUNDLE_IDENTIFIER: com.token.needverify
  PROVISIONING_PROFILE: 'NeedVerify_Dev'
  PROVISIONING_PROFILE_SPECIFIER: 'NeedVerify_Dev'
  PACKAGE_IOS: 1
